version: '3'
services:
  db:
    image: postgres:latest
    container_name: swift_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: swift_db1
    ports:
      - "5433:5432"
    networks:
      - swift-network

  app:
    build: .
    container_name: swift-api-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: prod
      spring.datasource.url: jdbc:postgresql://db:5433/swift_db1
      spring.datasource.username: postgres
      spring.datasource.password: password
    networks:
      - swift-network

networks:
  swift-network:
    driver: bridge
